[toolchain]
anchor_version = "0.32.1"
solana_version = "1.18.0"

[features]
seeds = false
skip-lint = false
resolution = true

[programs.localnet]
zenz_bridge = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.devnet]
zenz_bridge = "7ac8wtD5S9BRutHBMUoKMjpYepKSHVCgGaoN1etLjkd4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "backend/relayer-keypair-new.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/*"]
